# Generated by Django 4.2.2 on 2023-06-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_instituteslisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteslisting',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ApplyInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyinstitute', to='admissions.instituteslisting')),
            ],
        ),
    ]
