# Generated by Django 4.2.2 on 2023-06-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_buyproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productbuyer', to='ecom.productlisting'),
        ),
    ]
