# Generated by Django 4.2.2 on 2023-07-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_buyproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='featured',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
